### ISSUE TITLE
Dva matrix cannot eat cassidy flashbang

### ISSUE THREAD

**Issue by dubspool** [MaxwellJung/ow1_emulator#158] opened 2023-07-09 03:17 UTC

**Comment by MaxwellJung** [comment] 2023-07-09 03:18
Are you sure because you can deflect it.

**Comment by MrKingMichael** [comment] 2023-07-12 18:05
Cannot reproduce on my end.

**Comment by MaxwellJung** [comment] 2023-07-12 18:58
closing this issue since not actual bug

**Closed by MaxwellJung** 2023-07-12 18:58 UTC
Labels: bug
